IDS_ABORTING            			= Cancelando…
IDS_NO_UPDATE_FOUND     			= No se ha encontrado ninguna actualización.
IDS_ERROR_MESSAGE       			= Se ha producido un error. El servicio de actualización se ha detenido. Para obtener más información contacta con el soporte técnico de Ubisoft e incluye en tu email el texto del informe que aparece más abajo. Puedes pulsar en el botón Copiar al Portapapeles para que todo el texto se copie automáticamente y puedas pegarlo después en tu email.
IDS_DOWNLOAD_INCOMPLETE 			= No se ha podido completar la descarga de actualizaciones.
IDS_QUIT_BUTTON_CAPTION 			= Salir
IDS_DOWNLOAD_PROGRESS   			= %.0f/%.0f bytes recibidos (%.0f%%)
IDS_CURRENT_DOWNLOAD_FILE 			= Descargando %s…
IDS_CAN_RUN_UPDATE_FILE 			= Se ha encontrado y descargado al menos una actualización. ¿Quieres ponerla en marcha?
IDS_CAN_RUN_UPDATE_FILE_DLG_TITLE 	= ¡Se han encontrado actualizaciones!
IDS_INIT_FAILED_RES     			= Fallo al iniciar: faltan recursos gráficos.
IDS_THIS_FILE						= Este fichero
IDS_TOTAL							= Total
IDS_CANNOT_FIND_EXECUTABLE	 		= No se puede encontrar el ejecutable principal.\n
IDS_START_GAME_BUTTON_CAPTION   	= Iniciar juego

IDS_NETWORK_UNAVAILABLE				= La red no está disponible.\n
IDS_ADMINISTRATOR					= Debes tener permisos de administrador para poner en marcha esta aplicación.\n
IDS_YES 							= Sí
IDS_NO 								= No                  
IDS_BTN_ADVANCED                  	= Avanzada                                       
IDS_BTN_INSTA                     	= Instalar                                       
IDS_BTN_CLIPBORAD                 	= Copiar Al Portapapeles                         
IDS_TECHNICAL_LOG	 				= Registro técnico                               

IDS_LIB_ERR_USER_ABORT	 			= Descarga cancelada por el usuario.
IDS_LIB_ERR_PARTIALLY	 			= La descarga ha fallado parcialmente.
IDS_LIB_ERR_CANNOT_DELETE_FILE	 	= No se puede eliminar el archivo
IDS_LIB_MSG_PATCH_INFO	 			= Descargando información de actualización
IDS_LIB_MSG_GET_UPDATE_DOWNLOAD	 	= Intentando copiar información de actualización en
IDS_LIB_ERR_DWNLD_UPDATE_INFO		= No se ha podido descargar la información de actualización
IDS_LIB_ERR_CANNOT_CONTINUE			= El servicio de actualización no puede continuar.																																				
IDS_LIB_ERR_FILE_PARSING			= El análisis del archivo ha fallado.																																				
IDS_LIB_ERR_FILE_EMPTY	 			= Archivo vacío.																																				
IDS_LIB_ERR_FILE_TYPE	 			= Archivo de tipo incorrecto.																																				
IDS_LIB_ERR_FILE_FORMAT				= Formato de archivo incorrecto.																																				
IDS_LIB_MSG_NEW_UPDATE	 			= Descargando nueva actualización																																				
IDS_LIB_MSG_VERSION_FILE			= Descargando archivo de versión																																				
IDS_LIB_MSG_TRYING_VERSION_DOWNLOAD	= Intentando descargar archivo de versión de
IDS_LIB_MSG_DESTINATION	 			= Destino
IDS_LIB_MSG_SUCCES_VERSION	 		= Archivo de versión descargado correctamente.
IDS_LIB_ERR_CAB_NOT_TRUSTED	 		= El archivo de versión descargado no procede de una entidad de confianza y no se ejecutará.
IDS_LIB_ERR_DWNLD_VERSION_FILE	 	= No se ha podido descargar este archivo de versión
IDS_LIB_ERR_NO_INI	 				= Se ha producido un error al leer el archivo de versión. No se ha encontrado ningún archivo INI en el paquete.
IDS_LIB_ERR_NO_UPDATE_FOUND	 		= No se ha encontrado ninguna actualización para los destinos actuales:
IDS_LIB_MSG_FOUND_UPDATE	 		= Se ha encontrado una actualización
IDS_LIB_ERR_NO_HISTORY_1	 		= Se ha encontrado una actualización para el destino pero la versión no formaba parte del historial del producto. No puede seleccionarse la actualización.
IDS_LIB_ERR_NO_HISTORY_2	 		= No se ha encontrado el historial del destino:
IDS_LIB_MSG_ATTEMPTING_RESUME	 	= Se ha encontrado un archivo para el destino, se está intentando reanudar el proceso
IDS_LIB_MSG_FLAGGED_EXECUTION	 	= Se ha encontrado un archivo para el destino, ya marcado para ejecución. Omitiendo descarga
IDS_LIB_MSG_FLAGGED_DELETE	 		= Se ha encontrado un archivo para el destino, ya marcado para eliminación. Descarga fallida
IDS_LIB_ERR_NO_MIRRORS	 			= No se han encontrado duplicados para descarga.
IDS_LIB_MSG_TRYING_UPDATE_DOWNLOAD	= Intentando descargar archivo de actualización de
IDS_LIB_MSG_SUCCESS_UPDATE	 		= Archivo de actualización descargado correctamente.
IDS_LIB_ERR_OPEN_FILE	 			= No se puede abrir el archivo descargado. Imposible verificar la integridad del archivo.
IDS_LIB_MSG_CRC_VERIFY	 			= Verificando CRC de archivo descargado:
IDS_LIB_MSG_CRC_EXPECTED	 		= Se esperaba:
IDS_LIB_ERR_CRC_NOT_MATCH	 		= El CRC del archivo descargado no coincide con el CRC especificado en el archivo de versión.\nEl archivo descargado tiene un error.
IDS_LIB_MSG_PARTIAL_DOWNLOAD	 	= Archivo de actualización descargado correctamente. Guardando archivo para reanudar
IDS_LIB_ERR_FATAL_DOWNLOAD	 		= Error de descarga grave
IDS_LIB_ERR_DELETING	 			= Eliminando datos descargados.
IDS_LIB_ERR_LOCAL_TARGET	 		= No se ha podido extraer la información del archivo local para la actualización
IDS_LIB_ERR_UPDATE_NOT_TRUSTED	 	= El archivo de actualización descargado no procede de una entidad de confianza y no se ejecutará.
IDS_LIB_MSG_START_UPDATE	 		= Iniciando archivo de actualización
IDS_LIB_ERR_FAILED_START_UPDATE	 	= No se ha podido iniciar el archivo de actualización descargado.
IDS_LIB_ERR_EXE_NOT_FOUND	 		= No se ha encontrado el ejecutable de archivo de parche
IDS_LIB_ERR_NOT_ENOUGH_DISK_SPACE	= No hay suficiente espacio en disco
IDS_LIB_MSG_AVAILABLE				= Disponible
IDS_LIB_MSG_REQUIRED				= Requerido
IDS_LIB_MSG_MB						= MB (Megabytes)
IDS_ERR_FAILED_START_GAME			= No se ha podido iniciar el juego.
IDS_ERR_MISSING_REGISTRY_KEY        = No se ha encontrado información básica necesaria en el registro.
IDS_ERR_CONFIGURATION               = Error de configuración:
IDS_ERR_MISSING_GAMEID  			= 0x0002
IDS_ERR_MISSING_EXECUTABLE_PATH		= 0x0003
IDS_MSG_REINSTALL					= Es posible que el problema se solucione reinstalando el juego.
IDS_ERR_USER_CANCEL					= El usuario ha cancelado la operación.
IDS_LIB_ERR_CORRUPTED	            = ¿Archivo dañado?
